language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO=1.2.7
  - DJANGO=1.3.7
  - DJANGO=1.4.5
# command to install dependencies
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install pep8 --use-mirrors
  - pip install django-nose --use-mirrors
  - pip install -r src/requirements.txt --use-mirrors
before_script:
  - "pep8 --exclude=migrations --ignore=E501,E225,E128,E127 --exclude=thirdparty src"
  - "python bootstrap.py"
  - "python bin/buildout"
# command to run tests
script: python src/manage.py test
