dist: xenial
sudo: false

language: python

python:
  - "3.7"

addons:
  apt:
    update: true
    packages:
      - python3-pip
      - python3-setuptools

# This tests against all the versions of DB supported by Eden
env:
  - DB=mysql
  - DB=sqlite3
  - DB=postgres-9.6
  - DB=postgres-9.6+postgis
  - DB=postgres-10
  - DB=postgres-10+postgis

services:
  - mysql
  - postgresql

# Uncomment below to only test the master branch
# branches:
#  only:
#   - master

notifications:
 email: false

before_install:
  - python --version
  - pip install -U pip
  - chmod +x tests/travis/*

install:
  # Essential dependencies
  - pip install python-dateutil
  - pip install shapely
  - pip install lxml
  - pip install psycopg2
  # Generated dependencies
  - python tests/travis/generate_requirements_file.py tests/travis requirements.txt tests/travis/requirements.txt
  - pip install -r tests/travis/generated_requirements.txt
  # Install and configure web2py
  - tests/travis/install_web2py.sh
  # Install and configure Eden
  - tests/travis/install_eden.sh

before_script:
 - cd ../../web2py/
 - sudo chown -R ${USER} .
 - ./applications/eden/tests/travis/configure_db.sh
 #- cat ./applications/eden/models/000_config.py
 - python web2py.py -S eden -M -R applications/eden/static/scripts/tools/noop.py

script:
 - python web2py.py -S eden -M -R applications/eden/modules/unit_tests/suite.py

after_script:
 - echo  "Travis Test Result" $TRAVIS_TEST_RESULT
